version: 2

models:
  - name: fact_book
    description: "Fact table for books"
    columns:
      - name: book_id
        data_type: string
        description: "Unique identifier of book based on combination of book title and author"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: title
        data_type: string
        description: "Title of the book"

      - name: author_dim_id
        data_type: string
        description: "Dimenstion surrogate key for author"

      - name: genre_dim_id
        data_type: string
        description: "Dimenstion surrogate key for genre"

      - name: publishdate
        data_type: date
        description: "Original publishing date"

      - name: numberofpages
        data_type: int64
        description: "Number of pages"

      - name: ratingcount
        data_type: int64
        description: "Number of user ratings"

      - name: averagerating
        data_type: numeric
        description: "Average value of user ratings out of 5 stars"

      - name: reviewcount
        data_type: int64
        description: "Number of user reviews"

      - name: isbn
        data_type: string
        description: "International Standard Book Number, the universal code for the book"

      - name: insertdatetime
        data_type: datetime
        description: "Time when the record was inserted into the table"

  - name: dim_author
    description: "Dimension table for authors"
    columns:
      - name: author_dim_id
        data_type: string
        description: "Unique identifier for the author"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: author
        data_type: string
        description: "Author's full name"

      - name: insertdatetime
        data_type: datetime
        description: "Time when the record was inserted into the table"

  - name: dim_genre
    description: "Dimension table for genres"
    columns:
      - name: genre_dim_id
        data_type: string
        description: "Unique identifier for the genre"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: genre
        data_type: string
        description: "Genre for the book"

      - name: insertdatetime
        data_type: datetime
        description: "Time when the record was inserted into the table"

  - name: dim_date
    description: "Auto-generated dimension table for dates"
    columns:
      - name: date_day
        data_type: date
        description: ""

      - name: prior_date_day
        data_type: date
        description: ""

      - name: next_date_day
        data_type: date
        description: ""

      - name: prior_year_date_day
        data_type: date
        description: ""

      - name: prior_year_over_year_date_day
        data_type: date
        description: ""

      - name: day_of_week
        data_type: int64
        description: ""

      - name: day_of_week_iso
        data_type: int64
        description: ""

      - name: day_of_week_name
        data_type: string
        description: ""

      - name: day_of_week_name_short
        data_type: string
        description: ""

      - name: day_of_month
        data_type: int64
        description: ""

      - name: day_of_year
        data_type: int64
        description: ""

      - name: week_start_date
        data_type: date
        description: ""

      - name: week_end_date
        data_type: date
        description: ""

      - name: prior_year_week_start_date
        data_type: date
        description: ""

      - name: prior_year_week_end_date
        data_type: date
        description: ""

      - name: week_of_year
        data_type: int64
        description: ""

      - name: iso_week_start_date
        data_type: date
        description: ""

      - name: iso_week_end_date
        data_type: date
        description: ""

      - name: prior_year_iso_week_start_date
        data_type: date
        description: ""

      - name: prior_year_iso_week_end_date
        data_type: date
        description: ""

      - name: iso_week_of_year
        data_type: int64
        description: ""

      - name: prior_year_week_of_year
        data_type: int64
        description: ""

      - name: prior_year_iso_week_of_year
        data_type: int64
        description: ""

      - name: month_of_year
        data_type: int64
        description: ""

      - name: month_name
        data_type: string
        description: ""

      - name: month_name_short
        data_type: string
        description: ""

      - name: month_start_date
        data_type: date
        description: ""

      - name: month_end_date
        data_type: date
        description: ""

      - name: prior_year_month_start_date
        data_type: date
        description: ""

      - name: prior_year_month_end_date
        data_type: date
        description: ""

      - name: quarter_of_year
        data_type: int64
        description: ""

      - name: quarter_start_date
        data_type: date
        description: ""

      - name: quarter_end_date
        data_type: date
        description: ""

      - name: year_number
        data_type: int64
        description: ""

      - name: year_start_date
        data_type: date
        description: ""

      - name: year_end_date
        data_type: date
        description: ""