version: 2

models:
  - name: book_gold
    description: "Finalized operational table that with incremental updates"
    columns:
      - name: book_id
        data_type: string
        description: "Unique identifier of book based on combination of book title and author"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
  
      - name: title
        data_type: string
        description: "Title of the book"

      - name: author
        data_type: string
        description: "Author of the book"

      - name: isbn
        data_type: string
        description: "International Standard Book Number, the universal code for the book"

      - name: genre
        data_type: string
        description: "Genre of the book"

      - name: publishdate
        data_type: date
        description: "Original publishing date"

      - name: numberofpages
        data_type: int64
        description: "Number of pages"

      - name: ratingcount
        data_type: int64
        description: "Number of user ratings"

      - name: averagerating
        data_type: numeric
        description: "Average value of user ratings out of 5 stars"

      - name: reviewcount
        data_type: int64
        description: "Number of user reviews"

      - name: insertdatetime
        data_type: datetime
        description: "Time when the record was inserted into the table"

      - name: updatedatetime
        data_type: datetime
        description: "Time when the record was updated"



